language: go

go:
  - 1.6
  - 1.5
  - tip

install:
  - '[[ $TRAVIS_GO_VERSION == "1.5"  ]] || go get -u github.com/golang/lint/golint'
  - go get github.com/mattn/goveralls
  - go get -t ./...

script:
  - diff -u <(echo -n) <(gofmt -s -d ./)
  - diff -u <(echo -n) <(go vet ./...)
  - '[[ $TRAVIS_GO_VERSION == "1.5"  ]] || diff -u <(echo -n) <(golint ./...)'
  - go test -v -race -covermode=atomic -coverprofile=cover.out ./...
  - goveralls -coverprofile=cover.out -service=travis-ci
